### ISSUE TITLE
Event registration

### ISSUE THREAD

**Issue by Abhishek-Sai** [aravindvnair99/Aarohan2018#2]
The code is coming to the backend but we need to figure out how to add them into the database

**Comment by aravindvnair99** [comment]
@Abhishek-Sai event gets added. But overwriting occurs. Need to fix that and ensure data is written to database appropriately.

**Comment by RahulNK3498** [comment]
Event reg details not getting added to db
  Tried for 5 events
  
Event name needs to be chosen for every group created
  Would be great if, on choosing an event a new page opened and all details could be filled there and new submissions 
  also happened on that page

**Comment by aravindvnair99** [comment]
@RahulNK3498 All mentioned done and updated.

- New routes added for each event
- Redirects to event route instead of main page
- Drop down list available
- Data is being added to database
